apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: registry.35.186.226.213.nip.io/bcl/demo:latest
          imagePullPolicy: Always
          ports:
            - name: http-port
              containerPort: 8080
          env:
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: KUBERNETES_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: KUBERNETES_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KUBERNETES_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
---
apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: demo
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: demo-ingress
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#    ingress.kubernetes.io/rewrite-target: /
#spec:
#  rules:
#  - host: demo.192.168.99.100.nip.io
#    http:
#      paths:
#      - backend:
#          serviceName: demo
#          servicePort: 8080
#        path: /
