management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

kc:
  base-url: http://keycloak.35.193.56.167.nip.io/auth
  realm: POC
  realm-url: ${kc.base-url}/realms/${kc.realm}

spring:
  main:
    banner-mode: console
  security:
    oauth2:
      client:
        registration:
          demo:
            client-id: demo-app
            client-name: demo-appp
            client-secret: 4ebc8b9e-97ad-4aab-bbdc-044a563ef17e
            provider: keycloak
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak:
            authorization-uri: ${kc.realm-url}/protocol/openid-connect/auth
            jwk-set-uri: ${kc.realm-url}/protocol/openid-connect/certs
            token-uri: ${kc.realm-url}/protocol/openid-connect/token
            # would be cool if there was a end-session-uri to propagate logouts

            #  User info endpoint not needed since Keycloak uses self-contained value tokens
            #            user-info-uri: ${kc.realm-url}/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username