management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'


keycloak:
  auth-server-url: http://keycloak.35.193.56.167.nip.io/auth
  realm: POC

server:
  connection-timeout: 5000ms

spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: demo-app
            client-secret: 4ebc8b9e-97ad-4aab-bbdc-044a563ef17e
            clientName: Keycloak
            authorization-grant-type: authorization_code
            redirectUriTemplate: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
            - openid
            - profile
            - email
        provider:
          keycloak:
            authorization-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
            user-name-attribute: preferred_username