management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'

keycloak:
  auth-server-url: http://keycloak.35.193.56.167.nip.io/auth/
  resource: demo-app
  realm: POC
  public-client: true
  principal-attribute: preferred_username